### ISSUE TITLE
数据插入异常

### ISSUE THREAD

**Issue by wf744** [myhhub/stock#102]
应该是数据没有清洗干净，导致插入出错了。

`2024-11-30 17:02:19,023 database.insert_other_db_from_df处理异常：cn_stock_fund_flow_concept表(pymysql.err.DataError) (1366, "Incorrect double value: '-' for column `
instockdb`.`cn_stock_fund_flow_concept`.`change_rate` at row 456")
[SQL: INSERT INTO cn_stock_fund_flow_concept (date, name, change_rate, fund_amount, fund_rate, fund_amount_super, fund_rate_super, fund_amount_large, fund
_rate_large, fund_amount_medium, fund_rate_medium, fund_amount_small, fund_rate_small, stock_name, change_rate_5, fund_amount_5, fund_rate_5, fund_amount_
super_5, fund_rate_super_5, fund_amount_large_5, fund_rate_large_5, fund_amount_medium_5, fund_rate_medium_5, fund_amount_small_5, fund_rate_small_5, stoc
k_name_5, change_rate_10, fund_amount_10, fund_rate_10, fund_amount_super_10, fund_rate_super_10, fund_amount_large_10, fund_rate_large_10, fund_amount_me
dium_10, fund_rate_medium_10, fund_amount_small_10, fund_rate_small_10, stock_name_10) VALUES (%(date)s, %(name)s, %(change_rate)s, %(fund_amount)s, %(fun
d_rate)s, %(fund_amount_super)s, %(fund_rate_super)s, %(fund_amount_large)s, %(fund_rate_large)s, %(fund_amount_medium)s, %(fund_rate_medium)s, %(fund_amo
unt_small)s, %(fund_rate_small)s, %(stock_name)s, %(change_rate_5)s, %(fund_amount_5)s, %(fund_rate_5)s, %(fund_amount_super_5)s, %(fund_rate_super_5)s, %
(fund_amount_large_5)s, %(fund_rate_large_5)s, %(fund_amount_medium_5)s, %(fund_rate_medium_5)s, %(fund_amount_small_5)s, %(fund_rate_small_5)s, %(stock_n
ame_5)s, %(change_rate_10)s, %(fund_amount_10)s, %(fund_rate_10)s, %(fund_amount_super_10)s, %(fund_rate_super_10)s, %(fund_amount_large_10)s, %(fund_rate`

**Comment by wf744** [comment]
34978304.0, 'fund_rate_medium': 0.22, 'fund_amount_small': 349559680.0, 'fund_rate_small': 2.16, 'stock_name': '珂玛科技', 'change_rate_5': 1.04, 'fund_amount_5': -2492064864.0, 'fund_rate_5': -3.43, 'fund_amount_super_5': -918061072.0, 'fund_rate_super_5': -1.26, 'fund_amount_large_5': -1574003792.0, 'fund_rate_large_5': -2.17, 'fund_amount_medium_5': 55872256.0, 'fund_rate_medium_5': 0.08, 'fund_amount_small_5': 2232584368.0, 'fund_rate_small_5': 3.07, 'stock_name_5': 'C红四方', 'change_rate_10': -2.02, 'fund_amount_10': -5238581968.0, 'fund_rate_10': -3.44, 'fund_amount_super_10': -1465713936.0, 'fund_rate_super_10': -0.96, 'fund_amount_large_10': -3772868032.0, 'fund_rate_large_10': -2.48, 'fund_amount_medium_10': -186698752.0, 'fund_rate_medium_10': -0.12, 'fund_amount_small_10': 4640356752.0, 'fund_rate_small_10': 3.04, 'stock_name_10': 'C红四方'}  ... displaying 10 of 456 total bound parameter sets ...  {'date': '2024-11-29', 'name': '谷子经济', 'change_rate': -1.06, 'fund_amount': -2046376192.0, 'fund_rate': -4.84, 'fund_amount_super': -1013481472.0, 'fund_rate_super': -2.4, 'fund_amount_large': -1032894720.0, 'fund_rate_large': -2.45, 'fund_amount_medium': -20152064.0, 'fund_rate_medium': -0.05, 'fund_amount_small': 2005529600.0, 'fund_rate_small': 4.75, 'stock_name': '元隆雅图', 'change_rate_5': 8.24, 'fund_amount_5': -6620998800.0, 'fund_rate_5': -5.73, 'fund_amount_super_5': -3530811536.0, 'fund_rate_super_5': -3.06, 'fund_amount_large_5': -3090187264.0, 'fund_rate_large_5': -2.68, 'fund_amount_medium_5': 1171776768.0, 'fund_rate_medium_5': 1.01, 'fund_amount_small_5': 5552275968.0, 'fund_rate_small_5': 4.81, 'stock_name_5': '元隆雅图', 'change_rate_10': 8.24, 'fund_amount_10': -6620998800.0, 'fund_rate_10': -5.73, 'fund_amount_super_10': -3530811536.0, 'fund_rate_super_10': -3.06, 'fund_amount_large_10': -3090187264.0, 'fund_rate_large_10': -2.68, 'fund_amount_medium_10': 1171776768.0, 'fund_rate_medium_10': 1.01, 'fund_amount_small_10': 5552275968.0, 'fund_rate_small_10': 4.81, 'stock_name_10': '广博股份'}, {'date': '2024-11-29', 'name': '人形机器人', **'change_rate': '-',** 'fund_amount': '-', 'fund_rate': '-', 'fund_amount_super': '-', 'fund_rate_super': '-', 'fund_amount_large': '-', 'fund_rate_large': '-', 'fund_amount_medium': '-', 'fund_rate_medium': '-', 'fund_amount_small': '-', 'fund_rate_small': '-', 'stock_name': '-', 'change_rate_5': 0.0, 'fund_amount_5': '-', 'fund_rate_5': '-', 'fund_amount_super_5': '-', 'fund_rate_super_5': '-', 'fund_amount_large_5': '-', 'fund_rate_large_5': '-', 'fund_amount_medium_5': '-', 'fund_rate_medium_5': '-', 'fund_amount_small_5': '-', 'fund_rate_small_5': '-', 'stock_name_5': '软通动力', 'change_rate_10': 0.0, 'fund_amount_10': '-', 'fund_rate_10': '-', 'fund_amount_super_10': '-', 'fund_rate_super_10': '-', 'fund_amount_large_10': '-', 'fund_rate_large_10': '-', 'fund_amount_medium_10': '-', 'fund_rate_medium_10': '-', 'fund_amount_small_10': '-', 'fund_rate_small_10': '-', 'stock_name_10': '江苏雷利'}]]


以上加粗部分，预期是浮点数，但出现了'-'的值；
问题是在运行 python strategy_data_daily_job.py 时出现。

**Comment by XDAntenna** [comment]
所以你解决了吗？

**Comment by myhhub** [comment]
已修复
