### ISSUE TITLE
初始化了数据库，但是浏览器打开还是没有数据解决方案

### ISSUE THREAD

**Issue by tiantianaixuexi** [myhhub/stock#104]
![image](https://github.com/user-attachments/assets/e18e256c-7f35-4aa0-9c93-d4627db2caab)

浏览器能打开，但是里面是没有数据的，浏览器输入F12发现是  cn_stock_attention 基础表没有创建出来。复制 init_job.py 里面的 create_new_base_table() 去mysql手动创建发现是字符集不支持的原因，这个和mysql版本有关
![image](https://github.com/user-attachments/assets/6e3a3c7d-a6c2-4dba-a8a5-dc3aefbe8de3)

改成这样子，就可以创建表了 
`CREATE TABLE IF NOT EXISTS `cn_stock_attention` (
                                  `datetime` datetime(0) NULL DEFAULT NULL, 
                                  `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                  PRIMARY KEY (`code`) USING BTREE,
                                  INDEX `INIX_DATETIME`(`datetime`) USING BTREE
                                  ) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic`

然后再到浏览器点击就有数据

**Comment by CaiJingLong** [comment]
你的建表语句被 markdown 渲染了，直接复制无用

```sql
CREATE TABLE IF NOT EXISTS `cn_stock_attention`
(
    `datetime` datetime(0)                                                 NULL DEFAULT NULL,
    `code`     varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    PRIMARY KEY (`code`) USING BTREE,
    INDEX `INIX_DATETIME` (`datetime`) USING BTREE
) CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_general_ci
  ROW_FORMAT = Dynamic;
```

**Comment by myhhub** [comment]
获取最新，已强制utf8mb4，不会再出现字符的问题。
