### ISSUE TITLE
spreadjs 怎么弄呢？求教，感谢！issue61无帮助

### ISSUE THREAD

**Issue by Lambda-zhou** [myhhub/stock#108]
已经查看了issue61还是无效
使用环境py3.11，linux系统，创建隧道工具ngork运行代码如下：
# 启动Tornado应用
process = subprocess.Popen(["python", "web_service.py"]) # 运行你的Tornado应用

# 等待一段时间，确保Tornado服务器启动
time.sleep(5)

# 创建ngrok隧道
try:
    public_url = ngrok.connect(9988)
    print(f"ngrok隧道已创建，公网地址: {public_url}")
    print(f"你的股票应用可在 {public_url} 访问")
except Exception as e:
    print(f"ngrok连接失败: {e}")
    process.kill() # 终止Tornado应用

# 保持ngrok隧道运行，直到手动终止
try:
    process.wait()
except KeyboardInterrupt:
    ngrok.kill()
    print("ngrok隧道已关闭")

报错信息为spreadjs，无数据，已经运行了execute_daily_job.py，basic_data_daily_job.py。就是无数据

**Comment by Lambda-zhou** [comment]
> 谷歌一搜都是破解版。https://www.52pojie.cn/thread-1682637-1-1.html[ 重试    错误原因 ](javascript:void(0))

。。。。这帖子里也没有得下载的连接啊（全部都失效了）

**Comment by ohyeah521** [comment]
> > 谷歌一搜都是破解版。[https://www.52pojie.cn/thread-1682637-1-1.html[](https://www.52pojie.cn/thread-1682637-1-1.html%5B) 重试    错误原因 ](javascript:void(0))
> 
> 。。。。这帖子里也没有得下载的连接啊（全部都失效了）

你在仔细读读别人的回帖

**Comment by myhhub** [comment]
5楼

**Comment by Lambda-zhou** [comment]
> > > 谷歌一搜都是破解版。[https://www.52pojie.cn/thread-1682637-1-1.html 重试    错误原因 ](javascript:void(0))
> > 
> > 
> > 。。。。这帖子里也没有得下载的连接啊（全部都失效了）
> 
> 你在仔细读读别人的回帖

读了，然后发现很难弄，甚至不熟悉这方面的东西，只会点py和mysql。。。
