### ISSUE TITLE
大部分页面没有数据

### ISSUE THREAD

**Issue by shingoxray** [myhhub/stock#119]
昨天刚装的Docker版本，数据库有数据，但是页面不显示。

<img width="516" alt="图片" src="https://github.com/user-attachments/assets/8ffd0857-353c-4f47-9ec4-61501682e68e">
<img width="540" alt="图片" src="https://github.com/user-attachments/assets/c0e7098e-3361-4934-961d-790af51ef99a">

请教该如何解决？

**Comment by wx40217** [comment]
同样的问题 只有行业流出资金等少数几个页面有数据

**Comment by Lockey-J** [comment]
一样的问题。是不是4。0的bug。

**Comment by L0veHeather** [comment]
same

**Comment by myhhub** [comment]
你们是盘中运行的，有些模块缺省日期是昨天，选择当日就可以看到数据。
这些模块建议盘后运行数据更有参考价值。

**Comment by shingoxray** [comment]
> 你们是盘中运行的，有些模块缺省日期是昨天，选择当日就可以看到数据。 这些模块建议盘后运行数据更有参考价值。

今天不是盘中运行的了，但是数据显示更少了，只有每日ETF有数据显示，其它页面全无。

<img width="466" alt="图片" src="https://github.com/user-attachments/assets/11bdab73-fe43-4b19-9f8c-833aac9a5658">

<img width="536" alt="图片" src="https://github.com/user-attachments/assets/6a99478e-6512-498c-bc3f-50bf9fd56d68">

**Comment by CaiJingLong** [comment]
https://github.com/myhhub/stock/issues/104#issuecomment-2516313081

**Comment by wx40217** [comment]
https://github.com/myhhub/stock/issues/73 根据这个解决

**Comment by shingoxray** [comment]
> #73 根据这个解决

不是这个问题吧？

<img width="1054" alt="图片" src="https://github.com/user-attachments/assets/836d8085-1c4f-4068-9be9-525f8507a680">

<img width="536" alt="图片" src="https://github.com/user-attachments/assets/fc3cc8c7-6fa6-4ccd-81a6-c0c373c0c1fb">
