### ISSUE TITLE
ini_job.py的创建基础表的sql可不可以改一下。不然docker全新创建对接mariadb就会出现问题

### ISSUE THREAD

**Issue by Lockey-J** [myhhub/stock#120]
CREATE TABLE IF NOT EXISTS `cn_stock_attention`
(
    `datetime` datetime(0)                                                 NULL DEFAULT NULL,
    `code`     varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    PRIMARY KEY (`code`) USING BTREE,
    INDEX `INIX_DATETIME` (`datetime`) USING BTREE
) CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_general_ci
  ROW_FORMAT = Dynamic;

**Comment by Appilot-dev** [comment]
Andriod karma farming bot that runs on your device controlled from your dashboard.

We have made a reddit bot in 2024 but it functions through your phone remotely with a web dashboard no ADB or wire needed, a reddit karma bot that mimics human behavior through a learning script for the bot that shadows different humanized ways of managing an account of reddit.
You can check it's commenting features in [our repository](https://github.com/Appilot-dev/Reddit-Android-Karma-Farming-Bot)
How you can control the bot’s speed and never get banned again.

**Comment by myhhub** [comment]
已经修改
