### ISSUE TITLE
能不能把表结构导出来，动不动就找不到表

### ISSUE THREAD

**Issue by CodeVeteran** [myhhub/stock#129]
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_indicators_sell' doesn't exist")
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_indicators_sell' doesn't exist")
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_strategy_climax_limitdown' doesn't exist")

**Comment by myhhub** [comment]
没有表说明没有对应数据，有数据时会自动创表

**Comment by zhang7249** [comment]
周末运行加载不到数据，所以就报错？
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_bonus' doesn't exist")？

我刚才用镜像启动了InStockDbService，启动应用报错找不到数据库instockdb，我又删除了容器，增加了-p，dbeaver连上去手动建的库，然后有又提示上面的错误。。
