### ISSUE TITLE
网页内容是空的?

### ISSUE THREAD

**Issue by gzmoonkissss** [myhhub/stock#141]
version: '3.8'

services:
  instockdbservice:
    image: library/mariadb:latest
    container_name: InStockDbService
    volumes:
      - /data/mariadb/data:/var/lib/instockdb
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: no

  instock:
    image: mayanghua/instock:latest
    container_name: InStock
    depends_on:
      - instockdbservice
    ports:
      - "9988:9988"
    environment:
      db_host: instockdbservice
    restart: no

我用docker-component创建容器以后,可以正常访问网页,但是往里面是空的,这个是怎么回事?
![21209180223030](https://github.com/user-attachments/assets/2a0a43ff-0e4f-458a-91cb-2c8d59b0621e)

**Comment by gzmoonkissss** [comment]
我查了一下数据库,里面是已经有数据的,各种表和里面的当日数据都是有的,只是在前端的网页上显示不出来

**Comment by Ariesly** [comment]
请尝试统一下数据库排序规则
```sql
-- 查找并替换数据库中的所有 utf8mb4_uca1400_ai_ci
SELECT CONCAT('ALTER TABLE ', TABLE_SCHEMA, '.', TABLE_NAME, 
              ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'instockdb' 
# AND TABLE_COLLATION = 'utf8mb4_uca1400_ai_ci';
```

这个是参考操作
```sql
ALTER TABLE instockdb.cn_stock_spot_buy CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_top CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_high_tight_flag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_indicators_sell CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_keep_increasing CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_fund_flow_industry CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_parking_apron CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_low_atr CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_pattern CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_spot CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_indicators_buy CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_etf_spot CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_breakthrough_platform CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_fund_flow CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_bonus CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_enter CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_attention CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_selection CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_blocktrade CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_turtle_trade CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_indicators CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_fund_flow_concept CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_backtrace_ma250 CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_climax_limitdown CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

**Comment by gzmoonkissss** [comment]
`ALTER TABLE instockdb.cn_etf_spot CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_blocktrade CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_bonus CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_fund_flow CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_fund_flow_concept CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_fund_flow_industry CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_indicators CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_indicators_buy CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_pattern CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_selection CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_spot CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_spot_buy CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_backtrace_ma250 CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_breakthrough_platform CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_climax_limitdown CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_enter CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_high_tight_flag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_keep_increasing CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_parking_apron CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_strategy_turtle_trade CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE instockdb.cn_stock_top CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;`


我尝试 过,还是不行,下面是浏览器报错信息:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
data:1 Uncaught (in promise) some error happened
popup.js:15 Uncaught TypeError: Cannot read properties of undefined (reading 'onUpdated')
    at popup.js:15:13

**Comment by gzmoonkissss** [comment]
![1733797769163](https://github.com/user-attachments/assets/e79c8847-b5ba-4a1e-97b4-220541fb1b6a)
只有这三个是有内容的,不过是昨天修改数据库前也有内容,其他的都是空白的

**Comment by oneyh** [comment]
我也是一样，今天刚跑起来，只有这三条内容有数据。看了一下数据库，发现里面的表只有五张，正在研究每张表每个字段的含义，不知道这些表能否覆盖整个业务。

**Comment by myhhub** [comment]
获取最新，已强制utf8mb4，不会再出现字符的问题。

**Comment by gzmoonkissss** [comment]
我重新拉了镜像重装了一次,还是一样的情况,除了上面三个以外其他的没有数据

**Comment by sofs2005** [comment]
> 获取最新，已强制utf8mb4，不会再出现字符的问题。

解决了吗？我刚拉的今天的新镜像也是同样问题
