### ISSUE TITLE
股票策略数据，显示不了多日的收益率

### ISSUE THREAD

**Issue by zhangxyiang** [myhhub/stock#142]
![image](https://github.com/user-attachments/assets/400a7174-7c75-42dd-953b-4847d7cbb7e3)
如图可见，截图日期是2024.12.10，我2024.12.05的数据时按理说应该会显示 一日 二日 三日 等等的收益率信息。目前是没有显示的，接口返回没有报错，且没有返回rate_1,rate_2,rate_3等等的数据都是 null

**Comment by myhhub** [comment]
获取超时，再次执行

**Comment by zhangxyiang** [comment]
> 获取超时，再次执行

![image](https://github.com/user-attachments/assets/ae032740-403d-425e-b2b7-4bb1b1cdcb5e)
你好，我检查了数据库，发现是没有 更新后续的rate_1,rate_2等数据，请问是哪个脚本执行的，我再测试一下
