### ISSUE TITLE
没用docker部署，nginx在本地配置的还是要spreadjs授权啊,nginx配置如下

### ISSUE THREAD

**Issue by roczzz** [myhhub/stock#200]
GNU nano 7.2                                                                                                                            /etc/nginx/nginx.conf                                                                                                                                     
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

    server {
        listen 9989;
        server_name 192.168.0.2;

        location / {
            proxy_pass http://localhost:9988;  
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
    }
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        }

        # 静态文件服务
        location ~* ^/(css|fonts|img|js)/(.*)$ {
            alias /root/stock/instock/web/static/$1/$2;  
            expires max;
            log_not_found off;
        }

        error_page 500 502 503 504 = @error_handler;

        location @error_handler {
            return 500 "Internal Server Error: An error has occurred.";
        }
    }
}

**Comment by roczzz** [comment]
我把数据库服务器配置192.168.0.5上了，现在用192.168.0.2:9988访问还是要授权，该怎么弄？

**Comment by myhhub** [comment]
看历史问题
