### ISSUE TITLE
bat文件执行出错，参考了网上一些编码解决方法，无效

### ISSUE THREAD

**Issue by Buen16** [myhhub/stock#24]
![image](https://github.com/myhhub/stock/assets/133664414/a97bb6a4-4955-45d6-8b07-8ee9dd10ce89)

**Comment by Buen16** [comment]
在我的conda虚拟环境中执行也是出错

**Comment by Buen16** [comment]
![image](https://github.com/myhhub/stock/assets/133664414/45ae16d3-99c2-41ad-a0fa-73de2b8db2e4)

**Comment by Buen16** [comment]
我尝试了如下所有解决措施，无效：

检查文本编辑器中的文件编码

检查操作系统的默认编码

使用其他文本编辑器尝试保存文件为utf-8

尝试以命令行方式执行

**Comment by Buen16** [comment]
其他bat文件也是类似现象，都无法执行

**Comment by myhhub** [comment]
这个问题超出了本项目的范畴。 
.bat文件在DOS和Windows系统中是可执行文件，直接双击运行。
pycharm是开发python的ide工具，它可以直接运行.py文件。
