### ISSUE TITLE
表'Engine' object is not callable

### ISSUE THREAD

**Issue by wq57885** [myhhub/stock#28]
表'Engine' object is not callable

instock\job\backtest_data_daily_job.py

line 54 多了一个()

**Comment by myhhub** [comment]
修正

**Comment by Buen16** [comment]
> 修正

你修正个锤子？我6月9号就在 #25 给你说了这个代码错误，你阴阳怪气怼了我一句，现在才想起来修改？
![image](https://github.com/myhhub/stock/assets/133664414/6de557df-c87e-4959-a890-5d3048251c63)
