### ISSUE TITLE
获取历史数据的存储位置？

### ISSUE THREAD

**Issue by Zhihao66** [myhhub/stock#29]
作者你好，您的软件很棒！
我在用docker的版本，现在想获取历史数据，命令如下：
python basic_data_daily_job.py 2023-06-13
途中没有报错，但不知道存储的路径在哪里。
还有就是能否直接在网页版中添加历史信息的接口，或者在用命令行获取完成基础数据后可以在网页版的日期中看到自己下载的数据。
谢谢。

**Comment by myhhub** [comment]
“每日股票数据”是实时无历史数据的。历史交易数据(3年)在instock/cache/hist/目录里。
详细见：https://github.com/myhhub/stock#81%E6%89%A7%E8%A1%8C%E6%95%B0%E6%8D%AE%E6%8A%93%E5%8F%96%E5%A4%84%E7%90%86%E5%88%86%E6%9E%90%E8%AF%86%E5%88%AB
