### ISSUE TITLE
calculate_indicator.get_indicator处理异常：301170代码'code'

### ISSUE THREAD

**Issue by mufeng510** [myhhub/stock#32]
当前环境: conda python 3.10.11
刚开始了解项目，不清楚哪里出现问题。另外，使用批处理文件运行，但是没有报错退出，数据库一直不变，程序应该已经不再运行了，能否在控制台中添加提示。

执行的命令是 `python execute_daily_job.py 2023-6-26 2023-6-29`

![image](https://github.com/myhhub/stock/assets/30998460/50266cb5-eb5f-4426-8ca5-93200cbb2b2a)

**Comment by mufeng510** [comment]
更正一下，程序还在执行
![image](https://github.com/myhhub/stock/assets/30998460/5d8ee272-b610-4a21-af8d-a1cb368cf41e)

**Comment by myhhub** [comment]
已经修复。

> 当前环境: conda python 3.10.11 刚开始了解项目，不清楚哪里出现问题。另外，使用批处理文件运行，但是没有报错退出，数据库一直不变，程序应该已经不再运行了，能否在控制台中添加提示。
> 
> 执行的命令是 `python execute_daily_job.py 2023-6-26 2023-6-29`
> 
> ![image](https://user-images.githubusercontent.com/30998460/250023695-50266cb5-eb5f-4426-8ca5-93200cbb2b2a.png)

会跳过错误继续执行；
批量更新数据库；

**Comment by myhhub** [comment]
已修复

**Comment by lunfangyu** [comment]
> 已修复处理异常
![image_20241109181209](https://github.com/user-attachments/assets/cb06a111-a0d5-4be1-83ca-c35e953b3277)
执行枚举时间作业，仍然有此报错
