### ISSUE TITLE
哈喽，目前执行job里面很多文件报错，麻烦帮忙看一眼，万分感激

### ISSUE THREAD

**Issue by xzxsky** [myhhub/stock#34]
/Users/Sky/anaconda3/python.app/Contents/MacOS/python /Users/Sky/Desktop/WorkSpace/stock/instock/job/strategy_data_daily_job.py 
ERROR:root:stockfetch.fetch_stocks_trade_date处理异常：Native library not available at /Users/Sky/anaconda3/python.app/Contents/lib/python3.10/site-packages/py_mini_racer/libmini_racer.dylib
Exception ignored in: <function MiniRacer.__del__ at 0x125ca37f0>
Traceback (most recent call last):
  File "/Users/Sky/anaconda3/python.app/Contents/lib/python3.10/site-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
AttributeError: 'NoneType' object has no attribute 'mr_free_context'
ERROR:root:stockfetch.stock_hist_cache处理异常：300529代码Ran out of input
ERROR:root:stockfetch.stock_hist_cache处理异常：002363代码Ran out of input

**Comment by myhhub** [comment]
运行环境没有装好。
试着参考这个解决问题：https://github.com/sqreen/PyMiniRacer/issues/143
