### ISSUE TITLE
回测与自动交易问题

### ISSUE THREAD

**Issue by IT-JAVA** [myhhub/stock#35]
1. 想请教下，我根据文档中的信息进行策略回测，但是没有任何数据，也就是本地执行backtest_data_daily_job.py后，指标买入或指标卖出以及所有的策略，没有回测收益数据，想问下是我哪里执行的有问题嘛？
2. 想问下自动交易模块，我看了下代码是通过本地客户端进行登录的，是否能支持东财？目前看下来好像不支持

另外大佬能否添加下私人联系方式？诚心请教，万分感谢（wx: wishes_00）。之前邮件发你了好像没回
--
![image](https://github.com/myhhub/stock/assets/17808835/9f5e75ed-2503-44b6-b546-ae77d7631834)

**Comment by myhhub** [comment]
![mmexport1688950197707](https://github.com/myhhub/stock/assets/41766026/2ff5042c-f068-4683-9be1-1b322ccdd7f5)
1.策略时间后的交易日数据。
2.自动交易不支持东财

**Comment by IT-JAVA** [comment]
你那边执行回测也就是只在'backtest_data_daily_job.py'里执行run就可以了嘛？

**Comment by myhhub** [comment]
不执行backtest_data_daily_job.py怎么会有数据，所有代码都公开的，难不成骗你？
如果有人问你奇奇怪怪的问题，你怎样办？

**Comment by IT-JAVA** [comment]
OK，只是我这边执行完没有任何回测数据出来，所以请教下你

**Comment by myhhub** [comment]
确实没有，看日志确定问题，再找答案
