### ISSUE TITLE
为什么数据库里有内容，页面上却没有呢？

### ISSUE THREAD

**Issue by tumu123** [myhhub/stock#353]
![1](https://github.com/user-attachments/assets/9f4ee708-bd4c-43df-a593-5c8e5a94e9ad)
![2](https://github.com/user-attachments/assets/3de3ae68-9d03-4a50-98e7-4f65a0248075)
页面是一片空白，但数据库里面有数据的呀。

**Comment by myhhub** [comment]
选对应日期
