### ISSUE TITLE
为何数据库有数据，但是web不显示

### ISSUE THREAD

**Issue by welldo** [myhhub/stock#36]
安装了，但是web界面除了除了“每日etf数据”有数据，其他都是空的。但从 数据库中看有数据。

debian 8

![cn_etf_spot](https://github.com/myhhub/stock/assets/22337938/cb2216b6-19f6-4d41-9845-6bf874db0d9c)
![cn_stock_indicators](https://github.com/myhhub/stock/assets/22337938/27a24f90-bb0c-4a1e-94e3-7a8b0b73a259)
![cn_etf_spot_sql](https://github.com/myhhub/stock/assets/22337938/79b8042c-7f18-49b4-a62e-c3f5b149c2db)

![cn_stock_spot](https://github.com/myhhub/stock/assets/22337938/1eec1d53-0a54-4bb3-a343-b1d72266b619)
![cn_stock_spot_Sql](https://github.com/myhhub/stock/assets/22337938/3dd68940-5990-4d35-990d-92115723fae7)

**Comment by welldo** [comment]
![cn_stock_indicators_sql](https://github.com/myhhub/stock/assets/22337938/5b6c58e3-cd1b-4059-b5a4-ff4788012de1)

**Comment by myhhub** [comment]
7月11号没有数据，当然在7月11条件下没有东西显示。

**Comment by welldo** [comment]
数据库sql   https://tmp.link/f/64ae0c7529ea6

**Comment by welldo** [comment]
![微信截图_20230712103906](https://github.com/myhhub/stock/assets/22337938/477e6c3a-6f96-4cc7-82b3-d182f38187c6)

use  instockdb
SELECT * FROM cn_stock_spot WHERE date='2023-07-11'

结果如截图
但是web界面就是有问题

都是云服务器，华为hecs  和 oracle cloud 都一样。直接用的docker
![微信截图_20230712104055](https://github.com/myhhub/stock/assets/22337938/664aacc5-337a-4148-a477-e774574b0164)

**Comment by myhhub** [comment]
升级软件功能时，没考虑到旧版本自动升级缺“cn_stock_attention”表。
解决办法，任选一种：
1.  启动软件，打开下面页面点击“关注”按钮（它会自动创建cn_stock_attention表）：
http://localhost:9988/instock/data/indicators?code=000001&date=2023-07-12&name=%E5%B9%B3%E5%AE%89%E9%93%B6%E8%A1%8C
2.删除整个数据库。

**Comment by welldo** [comment]
方法1 已解决。。。

**Comment by myhhub** [comment]
已经修复错误，更新代码即可
