### ISSUE TITLE
我表示自己是小白，略微懂一些编程知识，想要请教问题。

### ISSUE THREAD

**Issue by C00LMIN** [myhhub/stock#38]
目前按照手册配置了，但是本地可视化服务跑不起来，想要请教一下怎么解决。有没有提供交流群大家一起学习进步一下的啊？没有的话强烈搭一个emmm，我主要需要利用这个系统回测一下交易策略的胜率。

**Comment by myhhub** [comment]
把可视化服务日志(stock_web.log)传上来，才能知道是什么问题

**Comment by C00LMIN** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
