### ISSUE TITLE
大佬也没建个群，我牵个头吧，有意向的可以加我，我去建个群 zhangwuge11011

### ISSUE THREAD

**Issue by jackson-cxs** [myhhub/stock#45]
我这边程序运行正常，我没用docker，docker打镜像一直报错，我是自己安装的包然后启动的。
微信 加我 ： zhangwuge11011

**Comment by shadowofgost** [comment]
我修改了docker可以直接使用github 的workflow工作，使用conda安装，用mkl的话numpy速度更快
