### ISSUE TITLE
docker: Error response from daemon: Cannot link to a non running container: /InStockDbService AS /InStock/InStockDbService

### ISSUE THREAD

**Issue by GGLEWO** [myhhub/stock#47]
![1699879087875](https://github.com/myhhub/stock/assets/43397792/0a5a54da-f299-4d65-8a54-bfd4c0745690)
第二个容器一起没起来，麻烦大佬帮忙看看！感谢

**Comment by GGLEWO** [comment]
![image](https://github.com/myhhub/stock/assets/43397792/a21cb63e-029f-4e3f-882a-7f8a7ff01be6)

**Comment by weigtman** [comment]
hello  遇到了相同的问题，现在已经解决，解决的思路是更换镜像，命令如下
docker run --name InStockDbService  -v /home/git/docker_by2.0/instork/mariadb/data:/var/lib/instockdb -e MYSQL_ROOT_PASSWORD=root -d docker.io/library/mariadb:10.8.2
