### ISSUE TITLE
跑不了bat文件是怎么回事

### ISSUE THREAD

**Issue by MaxsSpringBreeze** [myhhub/stock#53]
Active code page: 65001

D:\stock-master\stock-master\instock\bin>te_daily_job.py 2023-03-01
'te_daily_job.py' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>��建数据库，其他都支持批量作业------
'��建数据库，其他都支持批量作业------' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>基础数据非实时作业 python basic_data_other_daily_job.py
'基础数据非实时作业' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>K线形态作业 python klinepattern_data_daily_job.py
'K线形态作业' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>ta_daily_job.py
'ta_daily_job.py' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>est_data_daily_job.py
'est_data_daily_job.py' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>�作业中，请等待------
'�作业中，请等待------' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>python execute_daily_job.py
python: can't open file 'D:\\stock-master\\stock-master\\instock\\bin\\execute_daily_job.py': [Errno 2] No such file or directory

D:\stock-master\stock-master\instock\bin>pause
Press any key to continue . . .
Active code page: 65001

D:\stock-master\stock-master\instock\bin>.
'.' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>cho ------Web服务已启动，请不要关闭------
'cho' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>问地址 : http://localhost:9988/
'问地址' is not recognized as an internal or external command,
operable program or batch file.

D:\stock-master\stock-master\instock\bin>pause
Press any key to continue . . .

**Comment by feiwenxiong** [comment]
不要用中文路径，换成英文试试。
