### ISSUE TITLE
bat文件死活跑不动，全是乱码

### ISSUE THREAD

**Issue by xubing8** [myhhub/stock#57]
C:\Users\bisu5\Desktop\stock2-main\instock\bin>chcp 65001
'chcp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\bisu5\Desktop\stock2-main\instock\bin>.
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\bisu5\Desktop\stock2-main\instock\bin>ctivate
'ctivate' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\bisu5\Desktop\stock2-main\instock\bin>10
'10' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\bisu5\Desktop\stock2-main\instock\bin>cho ------Web鏈嶅姟宸插惎鍔紝璇蜂笉瑕佸叧闂?-----
'cho' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\bisu5\Desktop\stock2-main\instock\bin>闂湴鍧€ : http://localhost:9988/
'闂湴鍧€' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\bisu5\Desktop\stock2-main\instock\bin>pause
请按任意键继续. . .

**Comment by zwkkk** [comment]
运行.sh可以的
