### ISSUE TITLE
spreadjs 怎么弄呢？求教，感谢！

### ISSUE THREAD

**Issue by leafseelight** [myhhub/stock#61]
部署好，数据也抓到了，web报SpreadJs需要授权，有教程，或者链接吗？申请license后，配置在哪里呢？

**Comment by ma80000** [comment]
spreadjs是商业控件，访问域名使用localhsot或127.0.0.1，除了有试用水印没有其他限制。

**Comment by myhhub** [comment]
SpreadJS是商业控件，可以使用localhost、127.0.0.1本地域名访问，除了有水印提示无其他限制。

**Comment by leafseelight** [comment]
非常感谢，我试试代理

**Comment by myhhub** [comment]
据说这个有点料，我不懂，希望你能够成功。
https://raw.githubusercontent.com/TienPD3/tienpd3.github.io/main/website/scripts/spreadjs/gc.spread.sheets.all.16.0.2.min.latest.js

**Comment by leafseelight** [comment]
这个是破解版吗？我前面也有找过，不过照你说的localhost或127.0.0.1可以，我回头本机装个nginx代理即可，或者frp上服务器也行。





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myhhub/stock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [myhhub/stock] spreadjs 怎么弄呢？求教，感谢！ (Issue #61)





 
据说这个有点料，我不懂，希望你能够成功。
 https://raw.githubusercontent.com/TienPD3/tienpd3.github.io/main/website/scripts/spreadjs/gc.spread.sheets.all.16.0.2.min.latest.js

**Comment by myhhub** [comment]
> 这个是破解版吗？我前面也有找过，不过照你说的localhost或127.0.0.1可以，我回头本机装个nginx代理即可，或者frp上服务器也行。 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "myhhub/stock" ***@***.***&gt;; 发送时间:&nbsp;2024年6月24日(星期一) 下午5:32 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [myhhub/stock] spreadjs 怎么弄呢？求教，感谢！ (Issue #61) 据说这个有点料，我不懂，希望你能够成功。 https://raw.githubusercontent.com/TienPD3/tienpd3.github.io/main/website/scripts/spreadjs/gc.spread.sheets.all.16.0.2.min.latest.js — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

按那个方法可以的

**Comment by felixglow** [comment]
> 这个是xxx吗？我前面也有找过，不过照你说的localhost或127.0.0.1可以，我回头本机装个nginx代理即可，或者frp上服务器也行。

请教下nginx怎么弄呢，我部署阿里云，使用nginx代理的，公网访问就提示需要授权

**Comment by leafseelight** [comment]
nginx是要部署在本机，localhost代理到你的服务器就可以

**Comment by felixglow** [comment]
> nginx是要部署在本机，localhost代理到你的服务器就可以

嗯嗯，我开始想错了，现在悟了，感谢大佬

**Comment by heiyumiao** [comment]
求问大佬，我是docker部署的，用了bridge网络，网段172.17.0.1，用frp，nginx中转都不好使，一直显示未授权，有什么解决方案吗？

**Comment by leafseelight** [comment]
电脑装个nginx，localhost或者127.0.0.1代理到你的服务就可以了

**Comment by leafseelight** [comment]
应该是没影响，我是本机部署nginx，localhost代理到自己的服务器，是可以。不行你就换个方式，不要用docker。

**Comment by Lambda-zhou** [comment]
> 应该是没影响，我是本机部署nginx，localhost代理到自己的服务器，是可以。不行你就换个方式，不要用docker。

大佬解决了嘛？我用的ngrok不行。。。

**Comment by Lambda-zhou** [comment]
> > 电脑装个nginx，localhost或者127.0.0.1代理到你的服务就可以了
> 
> 不行诶，试过了，还是显示未授权。我怀疑docker容器内部访问的ip是172.17.0.1，不在它限定的局域网范围内。

朋友有试过ngork吗？
