### ISSUE TITLE
怎么按照30分钟K线数据来做分析呢?

### ISSUE THREAD

**Issue by AleDaDa** [myhhub/stock#62]
看了一下数据似乎存的是当前价格和每日价格, 那么如果想要按照30分钟K线怎么操作呢 ?

**Comment by myhhub** [comment]
需要自己扩展，读取每日分时行情数据，文件stock_hist_em.py，函数 stock_zh_a_hist_min_em

**Comment by AleDaDa** [comment]
stock_zh_a_hist_min_em 这样似乎是每次传入代码爬取相应信息, 我是想用30分钟K来做选股策略, 一口去大量传入是不是很可能要被东财加黑名单啊
