### ISSUE TITLE
请问为什么不能获取历史“每日股票数据”，只能获取昨日1天的“每日股票数据”

### ISSUE THREAD

**Issue by GloogTs** [myhhub/stock#66]
运行以下脚本全都运行过，2024-07-16的“每日股票数据”还是空的
python execute_daily_job.py 2024-07-16
python selection_data_daily_job.py 2024-07-16
python basic_data_daily_job.py 2024-07-16
python backtest_data_daily_job.py 2024-07-16
 python basic_data_other_daily_job.py 2024-07-16

**Comment by myhhub** [comment]
仔细查看使用说明：
https://github.com/myhhub/stock?tab=readme-ov-file#81%E6%89%A7%E8%A1%8C%E6%95%B0%E6%8D%AE%E6%8A%93%E5%8F%96%E5%A4%84%E7%90%86%E5%88%86%E6%9E%90%E8%AF%86%E5%88%AB
