### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by ggrsxx** [myhhub/stock#67]
大佬您好，我分别用Windows，Windows docker desktop ，ubuntu+docker搭建
每次一到运行时就会报数据库连接失败相关的问题
![QQ_1722612433700](https://github.com/user-attachments/assets/928d4158-6214-47a3-8059-464646a940a1)
我尝试过检查代码，但并没有解决问题
我又重装mysql版本，重置root密码，修改权限，都没能解决问题
请问我大概存在什么问题，我该如何联系您

**Comment by myhhub** [comment]
建议你用docker镜像，不依赖环境。
“Can’t connect to MySQL server on [IP]: ([Errno 111] Connection refused)”，说明无法在指定的主机和端口上连接到 MySQL 服务器。
解决步骤：
1.检查 MySQL 服务器是否正在运行。
2.检查 MySQL 服务器的主机和端口配置。
3.确保防火墙允许连接到 MySQL 服务器。
4.检查 MySQL 用户权限。

**Comment by Loliykon** [comment]
我和这个问题是类似的 现在是通过容器的方式就会显示连接不上数据库，但是如果直接在宿主机上运行python脚本就是OK的，请问这个是什么情况呢

**Comment by Loliykon** [comment]
![Image](https://github.com/user-attachments/assets/114bdbaa-c707-4956-ab97-520097c74096)

![Image](https://github.com/user-attachments/assets/42407ea7-0bdd-4be3-8814-4e5c9e06fbe0)
上面那副图是通过容器的方式，下面这一幅图是直接在宿主机上运行的，我确定数据库是已经打开了，感觉是容器和宿主机之间网络不通，但不知道该怎么处理，不知大佬可否指点一二
