### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by FENGSHI0312** [myhhub/stock#70]
![1726497195497](https://github.com/user-attachments/assets/c21d0639-421c-4a66-99b3-b81d252fac5f)

**Comment by myhhub** [comment]
run_web.bat
---------------------
chcp 65001
@echo off
cd %~dp0
cd .. @执行这条dos命令错误
cd web
python web_service.py
echo ------Web服务已启动，请不要关闭------
echo 访问地址 : http://localhost:9988/
pause
exit
