### ISSUE TITLE
打开股票指标买入，接口报错，缺少cn_stock_indicators_buy表

### ISSUE THREAD

**Issue by NiceMoon** [myhhub/stock#71]
![image](https://github.com/user-attachments/assets/3caef022-e5a7-4c8f-b830-0d78b36d63d7)

**Comment by myhhub** [comment]
删除数据库，然后执行任务，会自动创建数据库、数据表。

**Comment by Lucas-luwh** [comment]
没创建cn_stock_indicators_buy这张表  已经删除库了
