### ISSUE TITLE
支持mac吗

### ISSUE THREAD

**Issue by mafulong** [myhhub/stock#77]
支持mac吗

**Comment by mafulong** [comment]
mac运行会ERROR:root:stockfetch.fetch_stocks_trade_date处理异常：Native library not available at /Users/mafulong/github/stock/stock/venv/lib/python3.11/site-packages/py_mini_racer/libmini_racer.dylib
Exception ignored in: <function MiniRacer.__del__ at 0x127d34680>
Traceback (most recent call last):
  File "/Users/mafulong/github/stock/stock/venv/lib/python3.11/site-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

**Comment by myhhub** [comment]
软件跨平台的，肯定支持。
解决办法查看先前的issue：https://github.com/myhhub/stock/issues/63
