### ISSUE TITLE
部署后接口报错

### ISSUE THREAD

**Issue by gaye746560359** [myhhub/stock#79]
![image](https://github.com/user-attachments/assets/58781840-3a90-4bc6-9f29-217bea9bfecb)

**Comment by gaye746560359** [comment]
通过以下两个命令生成修改所有表排序规则的脚本并执行可以临时解决问题
-- 选择所有表
SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_table
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = 'instockdb';

-- 选择所有列
SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` MODIFY `', COLUMN_NAME, '` ', COLUMN_TYPE, ' CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_column
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'instockdb' AND COLLATION_NAME IS NOT NULL;

**Comment by myhhub** [comment]
由于中文及可能的特殊字符，本系统数据库字符集必须为utf8mb4，字符集排序规则为utf8mb4_general_ci。
由系统自动创建的数据库及表，字符集不太可能不对（多种运行环境下测试没复现该问题，代码也没问题）。

**Comment by chenbingiOS** [comment]
这个问题的确存在
使用 Docker 安装在云服务器 CentOS7.6-Docker26

**Comment by chenbingiOS** [comment]
> 通过以下两个命令生成修改所有表排序规则的脚本并执行可以临时解决问题 -- 选择所有表 SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_table FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'instockdb';
> 
> -- 选择所有列 SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` MODIFY `', COLUMN_NAME, '` ', COLUMN_TYPE, ' CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_column FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'instockdb' AND COLLATION_NAME IS NOT NULL;

这个2个命令是直接修改数据库表吗，是否需要重启数据库
重启了数据库，重启了Docker，还是同样的问题

**Comment by myhhub** [comment]
> 这个问题的确存在 使用 Docker 安装在云服务器 CentOS7.6-Docker26

数据库的字符集、排序规则是什么

**Comment by myhhub** [comment]
> > 通过以下两个命令生成修改所有表排序规则的脚本并执行可以临时解决问题 -- 选择所有表 SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_table FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'instockdb';
> > -- 选择所有列 SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` MODIFY `', COLUMN_NAME, '` ', COLUMN_TYPE, ' CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_column FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'instockdb' AND COLLATION_NAME IS NOT NULL;
> 
> 这个2个命令是直接修改数据库表吗，是否需要重启数据库 重启了数据库，重启了Docker，还是同样的问题


docker要外挂才是永久修改。

**Comment by chenbingiOS** [comment]
> > 这个问题的确存在 使用 Docker 安装在云服务器 CentOS7.6-Docker26
> 
> 数据库的字符集、排序规则是什么

使用默认Docker安装，没有修改数据集和排序规则，utf8mb4，utf8mb4_general_ci

**Comment by myhhub** [comment]
若是系统自动的创建表，会出字符集问题是由于mysql版本过低，utf8mb4最低mysql支持版本为5.5.3+。
utf8mb4 支持使用表情符号☺、��，表情数据是4个字节的字符。

**Comment by songjiahao-wq** [comment]
> 通过以下两个命令生成修改所有表排序规则的脚本并执行可以临时解决问题 -- 选择所有表 SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_table FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'instockdb';
> 
> -- 选择所有列 SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` MODIFY `', COLUMN_NAME, '` ', COLUMN_TYPE, ' CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;') AS alter_column FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'instockdb' AND COLLATION_NAME IS NOT NULL;

请问docker里如何使用这个操作，怎么没有找到
