### ISSUE TITLE
部署后缺少四张表

### ISSUE THREAD

**Issue by gaye746560359** [myhhub/stock#80]
http://localhost:9988/instock/api_data?name=cn_stock_indicators_sell&date=2024-10-17
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_indicators_sell' doesn't exist")

http://localhost:9988/instock/api_data?name=cn_stock_strategy_low_backtrace_increase&date=2024-10-17
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_strategy_low_backtrace_increase' doesn't exist")

http://localhost:9988/instock/api_data?name=cn_stock_strategy_climax_limitdown&date=2024-10-17
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_strategy_climax_limitdown' doesn't exist")

http://localhost:9988/instock/api_data?name=cn_stock_strategy_low_atr&date=2024-10-17
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_strategy_low_atr' doesn't exist")

**Comment by myhhub** [comment]
正常。没有创建的表，说明暂时没有对应数据，有数据会自动创建。
