### ISSUE TITLE
mac端安装没有数据

### ISSUE THREAD

**Issue by medivh-xiong** [myhhub/stock#83]
运行的时候有个警告：WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

是不是因为这个原因导致，web能打开，但是进去什么数据都没有

**Comment by myhhub** [comment]
警告表示拉取的Docker镜像是为linux/amd64架构设计的，而Mac M1使用的是linux/arm64/v8架构。
要解决这个问题，可以强制Docker使用适合ARM架构的镜像，在启动命令加入 --platform linux/arm64/v8 即可。
如：
docker run -dit --platform linux/arm64/v8 --name InStock \
    -p 9988:9988 \
    -e db_host=localhost \
    -e db_user=root \
    -e db_password=root \
    -e db_database=instockdb \
    -e db_port=3306 \
    mayanghua/instock:latest
