### ISSUE TITLE
关于与聚宽策略的交互

### ISSUE THREAD

**Issue by harrycuidm** [myhhub/stock#84]
首先感谢大佬提供这么完善的系统，小小建议一下，能否将聚宽的策略融入到系统中，比如将聚宽策略保存成py文件，然后保存到strategies中，自动化交易模块可以使用这个策略。

**Comment by XyhBill** [comment]
> 首先感谢大佬提供这么完善的系统，小小建议一下，能否将聚宽的策略融入到系统中，比如将聚宽策略保存成py文件，然后保存到strategies中，自动化交易模块可以使用这个策略。

问下 第一次运行就会初始化cn_stock_attention这张表吗？stock_web.log日志提示找不到这张表

**Comment by dominicx** [comment]
> > 首先感谢大佬提供这么完善的系统，小小建议一下，能否将聚宽的策略融入到系统中，比如将聚宽策略保存成py文件，然后保存到strategies中，自动化交易模块可以使用这个策略。
> 
> 问下 第一次运行就会初始化cn_stock_attention这张表吗？stock_web.log日志提示找不到这张表

需要手工建立一下这个表。

**Comment by myhhub** [comment]
> > 首先感谢大佬提供这么完善的系统，小小建议一下，能否将聚宽的策略融入到系统中，比如将聚宽策略保存成py文件，然后保存到strategies中，自动化交易模块可以使用这个策略。
> 
> 问下 第一次运行就会初始化cn_stock_attention这张表吗？stock_web.log日志提示找不到这张表
肯定会，详细参考：
https://github.com/myhhub/stock/issues/75
