### ISSUE TITLE
网页只有小部分页面有数据

### ISSUE THREAD

**Issue by apas008** [myhhub/stock#85]
数据库数据表也有 但是除了资金流向三个有数据 其余都没有
<img width="951" alt="image" src="https://github.com/user-attachments/assets/7e0b040b-1dc9-4b5e-9eb9-600230e59ad3">

**Comment by apas008** [comment]
是因为instockdb.cn_stock_attention 这张表没有数据 自己在数据库加上后 创建了一条数据 就可以看了

**Comment by ar0c** [comment]
> 是因为instockdb.cn_stock_attention 这张表没有数据 自己在数据库加上后 创建了一条数据 就可以看了

请问随便写一条就可以了吗？我加了一条好像还是不行
