### ISSUE TITLE
cn_stock_fund_flow_concept表插入数据异常

### ISSUE THREAD

**Issue by lunfangyu** [myhhub/stock#86]
![image_20241112201425](https://github.com/user-attachments/assets/00a60748-5cdc-4131-bb22-4cf512ed5ca2)
![image_20241112201452](https://github.com/user-attachments/assets/59d36380-3490-4da4-8bd0-ff886555ad80)

cn_stock_fund_flow_concept这个表的字段 change_rate 原来是float类型，插入报错，我以为长度不够，改为decimal ，结果还是报错，这回报错提示是因为有个值是“-”；
所以建议在插入前对值的类型进行判断，非数据类型的要处理掉。

**Comment by lunfangyu** [comment]
![image_20241112202320](https://github.com/user-attachments/assets/ff49dab2-5bd6-4ecd-a318-16fdde64f09d)
"Table 'instockdb.cn_stock_strategy_low_backtrace_increase' doesn't exist
报错表cn_stock_strategy_low_backtrace_increase不存在。
![image_20241112202420](https://github.com/user-attachments/assets/f99ba007-aa68-475f-bd7f-ad319173b9a9)
我把代码下载下来做了全文搜索，也没找到建表语句。 请问下和这个表相关的建表逻辑是删除了吗

**Comment by lunfangyu** [comment]
![image_20241112205849](https://github.com/user-attachments/assets/4f43ff03-b910-46ce-a061-6fc0feffb5a3)
把 change_rate 改为了varchar类型，其他字段也有这种情况：Incorrect integer value: '-' for column 'fund_amount' at row 244

**Comment by oldbai555** [comment]
![image](https://github.com/user-attachments/assets/4b5d5d75-a29e-4672-bae8-633d35784302)
同问 我也遇上了这个问题 在想要怎么修改

**Comment by myhhub** [comment]
问题已经没有。新增“蚂蚁金服”概念，昨天没有数据，今天已经有数据。

碰到这种数据不规范问题要解决源头，转换一下数据即可，temp_df['今日涨跌幅'] = pd.to_numeric(temp_df['今日涨跌幅'])。
