### ISSUE TITLE
 calculate_indicator.get_indicator处理异常：301606代码'code'

### ISSUE THREAD

**Issue by dominicx** [myhhub/stock#88]
运行后查看日志 InStock/instock/log/stock_execute_job.log 
显示大量的 “calculate_indicator.get_indicator处理异常：” 错误。

都是  301606代码'code' 这样的。
稍微看了一下代码 应该是 execute_daily_job.py 中
        # # 第3.2步创建股票指标数据表
        executor.submit(gdj.main)
调用 indicators_data_daily_job.py  run_check 出现问题。

请问怎么查看完整日志呢，我看很多地方都有logger。但是出错之后没法看trace

**Comment by myhhub** [comment]
不是系统的问题。
