### ISSUE TITLE
数据库报错处理

### ISSUE THREAD

**Issue by jetamie** [myhhub/stock#94]

**Comment by wangsuozhu1** [comment]
少了几张表没初始化出来，咋处理，是收费的吗？

**Comment by yuzlor** [comment]
> 少了几张表没初始化出来，咋处理，是收费的吗？

你先执行python execute_daily_job.py试试，应该是没抓数据吧

**Comment by myhhub** [comment]
完全开源，不收费。这问题看历史Issues可以解决
