### ISSUE TITLE
cn_stock_strategy_low_backtrace_increase 提示不存在，好像也不会自动创建，是什么情况？

### ISSUE THREAD

**Issue by wangsuozhu1** [myhhub/stock#96]
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/b39d0a3d-a681-476a-b789-e0824f12f88e">
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/6d59c357-1caf-4d39-b756-5c3cc41faa0b">
<img width="845" alt="image" src="https://github.com/user-attachments/assets/c5d72820-830d-4e22-9d85-edc4b1c3c056">
哪位大佬可以帮忙看看

**Comment by myhhub** [comment]
没有问题，暂时没有符合条件的数据，有数据时会自动建表。
