### ISSUE TITLE
接口报错"Table 'instockdb.cn_stock_attention' doesn't exist"

### ISSUE THREAD

**Issue by wei-zhen-wang** [myhhub/stock#97]
![image](https://github.com/user-attachments/assets/bdd96b76-a203-451b-8c04-6b543cb3ab85)

**Comment by tiantianaixuexi** [comment]
mysql版本的问题，新版的字符集不支持改成这个手动在库里面创建表即可

'CREATE TABLE IF NOT EXISTS cn_stock_attention(datetimedatetime(0) NULL DEFAULT NULL, code varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, PRIMARY KEY (code) USING BTREE, INDEX INIX_DATETIME(datetime) USING BTREE ) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic'

**Comment by wei-zhen-wang** [comment]
好的，已解决，谢谢

**Comment by b2522** [comment]
我改了一下，用这个执行可以创建attention表

`CREATE TABLE cn_stock_attention (
    datetime datetime(0) NULL DEFAULT NULL,
    code varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    INDEX idx_datetime (datetime) USING BTREE,
    PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=Dynamic;`

**Comment by myhhub** [comment]
看历史Issues可以解决该问题
