### ISSUE TITLE
大佬求解决 执行/usr/local/bin/python3 /data/InStock/instock/job/klinepattern_data_daily_job.py报错

### ISSUE THREAD

**Issue by wyxiong431** [myhhub/stock#98]
执行/usr/local/bin/python3 /data/InStock/instock/job/klinepattern_data_daily_job.py报错

stockfetch.fetch_stock_top_data处理异常：HTTPConnectionPool(host='vip.stock.finance.sina.com.cn', port=80): Max retries exceeded with url: /q/go.php/vLHBData/kind/ggtj/index.phtml?last=5&p=6 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f392ad4c610>: Failed to resolve 'vip.stock.finance.sina.com.cn' ([Errno -3] Temporary failure in name resolution)"))

**Comment by cmy2008** [comment]
更换国内dns

**Comment by myhhub** [comment]
偶尔会拒绝访问，再运行一次
